; Generated by Force Forth Cross Compiler v1.0
; Target: ysd8800  Thread: subroutine
;

    .org $0020

; DEFER dispatch helper
_DEFER_TMP:
    DW   0
_DEFER_DISPATCH:
    LDW  A, [_DEFER_TMP]
    ; indirect jump: stub
    RET
DEFER_DEFAULT:
    RET

answer               EQU $002A
THREE                EQU $0003

; VARIABLE counter
    .org $E200
VAR_counter:
    DW   0
WORD_counter:
    LDW  A, #$E200
    SUBI X, #2
    STW  A, [X]
    RET

; VALUE cur_task
    .org $E202
VAL_cur_task:
    DW   $0000
WORD_cur_task:
    LDW  A, #$E202
    SUBI X, #2
    STW  A, [X]
    RET

; DEFER irq_disable
    .org $E204
VEC_irq_disable:
    DW   DEFER_DEFAULT
WORD_irq_disable:
    LDW  A, [$E204]
    ; indirect call via vector
    ; TODO: JSR [A]  (要アーキテクチャ対応)
    STW  A, [_DEFER_TMP]
    JSR  _DEFER_DISPATCH
    RET

; DEFER irq_enable
    .org $E206
VEC_irq_enable:
    DW   DEFER_DEFAULT
WORD_irq_enable:
    LDW  A, [$E206]
    ; indirect call via vector
    ; TODO: JSR [A]  (要アーキテクチャ対応)
    STW  A, [_DEFER_TMP]
    JSR  _DEFER_DISPATCH
    RET

; --- double ---
WORD_double:
    ; PRIM TWO-STAR
LDW  A, [X]
LDW  B, #1
SHL  A, B
STW  A, [X]
    RET

; --- square ---
WORD_square:
    ; PRIM DUP
LDW  A, [X]
SUBI X, #2
STW  A, [X]
    ; PRIM STAR
; ソフトウェア乗算 (Layer1 FORTH_MUL相当)
LDW  A, [X]
ADDI X, #2
LDW  B, [X]
; A=multiplicand B=multiplier → 結果をBに
STW  A, [_MUL_WK_A]
STW  B, [_MUL_WK_B]
LDW  A, #0
LDW  B, [_MUL_WK_B]
LDW  B, [_MUL_WK_A]
JSR  _PRIM_MUL
STW  A, [X]
    RET

; --- abs_val ---
WORD_abs_val:
    ; PRIM DUP
LDW  A, [X]
SUBI X, #2
STW  A, [X]
    ; PRIM ZERO-LT
LDW  A, [X]
CMPI A, #0
LDW  A, #0
BGE  _zlt_f
LDW  A, #$FFFF
_zlt_f:
STW  A, [X]
    LDW  A, [X]
    ADDI X, #2
    CMPI A, #0
    BEQ  .L0
    ; PRIM NEGATE
LDW  A, [X]
LDW  B, #0
SUB  B, A
STW  B, [X]
.L0:
    RET

; --- max2 ---
WORD_max2:
    ; PRIM OVER
LDW  A, [X + #2]
SUBI X, #2
STW  A, [X]
    ; PRIM OVER
LDW  A, [X + #2]
SUBI X, #2
STW  A, [X]
    ; PRIM LT
LDW  A, [X]
ADDI X, #2
LDW  B, [X]
CMP  B, A
LDW  A, #0
BGE  _lt_f
LDW  A, #$FFFF
_lt_f:
STW  A, [X]
    LDW  A, [X]
    ADDI X, #2
    CMPI A, #0
    BEQ  .L1
    ; PRIM SWAP
LDW  A, [X]
LDW  B, [X + #2]
STW  A, [X + #2]
STW  B, [X]
.L1:
    ; PRIM DROP
ADDI X, #2
    RET

; --- count_down ---
WORD_count_down:
.L2:
    ; PRIM DUP
LDW  A, [X]
SUBI X, #2
STW  A, [X]
    ; PRIM ZERO-GT
LDW  A, [X]
CMPI A, #0
LDW  A, #0
BLE  _zgt_f
LDW  A, #$FFFF
_zgt_f:
STW  A, [X]
    LDW  A, [X]
    ADDI X, #2
    CMPI A, #0
    BEQ  .L3
    ; PRIM ONE-MINUS
LDW  A, [X]
SUBI A, #1
STW  A, [X]
    JMP  .L2
.L3:
    ; PRIM DROP
ADDI X, #2
    RET

; --- wait_zero ---
WORD_wait_zero:
.L4:
    JSR  WORD_counter
    LDW  A, [X]
    LDW  A, [A]
    STW  A, [X]
    ; PRIM ZERO-EQ
LDW  A, [X]
CMPI A, #0
LDW  A, #0
BNE  _zeq_f
LDW  A, #$FFFF
_zeq_f:
STW  A, [X]
    LDW  A, [X]
    ADDI X, #2
    CMPI A, #0
    BEQ  .L4
    RET

; --- clamp ---
WORD_clamp:
    ; PRIM ROT
LDW  A, [X + #4]
LDW  B, [X + #2]
STW  B, [X + #4]
LDW  B, [X]
STW  B, [X + #2]
STW  A, [X]
    ; PRIM OVER
LDW  A, [X + #2]
SUBI X, #2
STW  A, [X]
    ; PRIM OVER
LDW  A, [X + #2]
SUBI X, #2
STW  A, [X]
    ; PRIM LT
LDW  A, [X]
ADDI X, #2
LDW  B, [X]
CMP  B, A
LDW  A, #0
BGE  _lt_f
LDW  A, #$FFFF
_lt_f:
STW  A, [X]
    LDW  A, [X]
    ADDI X, #2
    CMPI A, #0
    BEQ  .L5
    ; PRIM DROP
ADDI X, #2
    ; PRIM OVER
LDW  A, [X + #2]
SUBI X, #2
STW  A, [X]
    JMP  .L6
.L5:
    ; PRIM SWAP
LDW  A, [X]
LDW  B, [X + #2]
STW  A, [X + #2]
STW  B, [X]
    ; PRIM OVER
LDW  A, [X + #2]
SUBI X, #2
STW  A, [X]
    ; PRIM OVER
LDW  A, [X + #2]
SUBI X, #2
STW  A, [X]
    ; PRIM GT
LDW  A, [X]
ADDI X, #2
LDW  B, [X]
CMP  B, A
LDW  A, #0
BLE  _gt_f
LDW  A, #$FFFF
_gt_f:
STW  A, [X]
    LDW  A, [X]
    ADDI X, #2
    CMPI A, #0
    BEQ  .L7
    ; PRIM DROP
ADDI X, #2
    JMP  .L8
.L7:
    ; PRIM NIP
LDW  A, [X]
ADDI X, #2
STW  A, [X]
    ; PRIM NIP
LDW  A, [X]
ADDI X, #2
STW  A, [X]
.L8:
.L6:
    ; PRIM NIP
LDW  A, [X]
ADDI X, #2
STW  A, [X]
    RET

; --- di_impl ---
WORD_di_impl:
    RET

; --- ei_impl ---
WORD_ei_impl:
    RET

; IS ['] <- [']
    LDW  A, WORD_[']
    STW  A, [VEC_[']]

; IS 5 <- 5
    LDW  A, WORD_5
    STW  A, [VEC_5]
