#!/usr/bin/env python3
# mk_v4_regress_tb.py  v1.0  (2026-07-12)
# V3.5 回帰TB -> V4 membus 用へ機械変換する（KY48 対策）
#
# 変換内容:
#   (1) module 名   tb_cpu_v35xxx  -> tb_cpu_v4xxx
#   (2) membus 名   ysd8800_v35_membus_v0_1 -> ysd8800_v4_membus_v0_1
#   (3) V4 新規ポート6本を明示結線（未接続放置=偽合格の防止）
#         irq_src_stor      : 0 固定（V6まで）
#         irq1_o            : TB net へ（未使用だが必ず受ける）
#         uart_rx_valid_i   : 0 固定（回帰中はRXを入れない）
#         uart_rx_data_i    : 0 固定
#         uart_tx_valid_o   : TB net へ
#         uart_tx_data_o    : TB net へ
#   (4) 上記 net の宣言を追加
#
# ★注意: irq_in は【CPU側】の入力であり membus 側ポートではない。
#         V4 では irq1_o を irq_in へ結線【しない】（回帰は割込なしのため
#         V3.5 と完全同一条件を保つ = デグレ検出の等価性を維持する）。
#         割込経路の検証は S5（結合TB）で行う。

import re, sys, os

SRCS = [
    ("tb_cpu_v35regress_poc.sv",  "tb_cpu_v4regress_poc.sv"),
    ("tb_cpu_v35mem_poc.sv",      "tb_cpu_v4mem_poc.sv"),
    ("tb_cpu_v35boundary_poc.sv", "tb_cpu_v4boundary_poc.sv"),
    ("tb_cpu_v35mmu_v0_1.sv",     "tb_cpu_v4mmu_v0_1.sv"),
]

NEW_NETS = """
    // ---- ★V4追加: membus 新規ポート受け net（KY48）★ ----
    logic        v4_irq1_o;
    logic        v4_uart_tx_valid_o;
    logic [7:0]  v4_uart_tx_data_o;
"""

NEW_CONNS = """        .irq_src_stor(1'b0),
        .irq1_o(v4_irq1_o),
        .uart_rx_valid_i(1'b0),
        .uart_rx_data_i(8'h00),
        .uart_tx_valid_o(v4_uart_tx_valid_o),
        .uart_tx_data_o(v4_uart_tx_data_o),
"""

for src, dst in SRCS:
    with open(src) as f:
        t = f.read()

    old_mod = re.search(r'^module\s+(tb_cpu_v35\w+)\s*;', t, re.M).group(1)
    new_mod = old_mod.replace("v35", "v4", 1)

    # (1) module 名
    t = t.replace(old_mod, new_mod)

    # (3)(4) membus インスタンス直前に net 宣言を挿入
    inst_pat = r'(\s*)ysd8800_v35_membus_v0_1(\s*#\(.*?\)\)\s*)(\w+)\s*\(\n'
    m = re.search(inst_pat, t)
    if not m:
        print(f"!! membus inst not found in {src}")
        sys.exit(1)

    indent = m.group(1)
    replacement = (NEW_NETS + indent + "ysd8800_v4_membus_v0_1"
                   + m.group(2) + m.group(3) + " (\n" + NEW_CONNS)
    t = t[:m.start()] + replacement + t[m.end():]

    # ヘッダに変換痕跡を残す
    t = ("// [AUTO-GENERATED by mk_v4_regress_tb.py v1.0 from %s]\n"
         "// V4 membus (ysd8800_v4_membus_v0_1) 用に機械変換。KY48 準拠。\n" % src) + t

    with open(dst, "w") as f:
        f.write(t)
    print("generated: %s  (module %s -> %s)" % (dst, old_mod, new_mod))
