/*
 * YSD8800 ISA2.0 Forth Cross Compiler
 * STC (Subroutine Threaded)
 *
 * 制約:
 *  - 間接呼び出しなし
 *  - ISA2.0命令のみ出力
 *
 * build:
 *   gcc -std=c99 -O2 forthcc.c -o forthcc
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>

#define MAX_TOKENS 1024
#define MAX_TOKEN  64

static char *tokens[MAX_TOKENS];
static int ntokens = 0;

static int pos = 0;

/* =========================
 * ユーティリティ
 * ========================= */

static char *strdup2(const char *s)
{
    char *p = malloc(strlen(s)+1);
    strcpy(p, s);
    return p;
}

static void tokenize(FILE *fp)
{
    char buf[MAX_TOKEN];
    while (fscanf(fp, "%63s", buf) == 1) {
        tokens[ntokens++] = strdup2(buf);
    }
}

static int is_number(const char *s)
{
    if (*s == '-' || *s == '+') s++;
    if (!isdigit(*s)) return 0;
    while (*s) {
        if (!isdigit(*s)) return 0;
        s++;
    }
    return 1;
}

/* =========================
 * 出力
 * ========================= */

static void emit_header(void)
{
    printf("; ---- generated by forthcc ----\n");
    printf(".org 0800\n\n");
}

static void emit_number(const char *s)
{
    int v = atoi(s);

    printf("    LDW A,#%d\n", v);
    printf("    PUSH A\n");
}

static void emit_word(const char *w)
{
    /* そのままJSR */
    printf("    JSR %s\n", w);
}

/* =========================
 * コロン定義
 * ========================= */

static void compile_colon(void)
{
    if (pos >= ntokens) {
        fprintf(stderr, "error: ':' without name\n");
        exit(1);
    }

    char *name = tokens[pos++];

    printf("\n%s:\n", name);

    while (pos < ntokens) {
        char *t = tokens[pos++];

        if (strcmp(t, ";") == 0) {
            printf("    RET\n");
            return;
        }

        if (is_number(t)) {
            emit_number(t);
        } else {
            emit_word(t);
        }
    }

    fprintf(stderr, "error: missing ';'\n");
    exit(1);
}

/* =========================
 * トップレベル
 * ========================= */

static void compile_top(void)
{
    printf("\nSTART:\n");

    while (pos < ntokens) {
        char *t = tokens[pos++];

        if (strcmp(t, ":") == 0) {
            compile_colon();
            continue;
        }

        if (is_number(t)) {
            emit_number(t);
        } else {
            emit_word(t);
        }
    }

    printf("    RET\n");
}

/* =========================
 * main
 * ========================= */

int main(int argc, char **argv)
{
    if (argc < 2) {
        fprintf(stderr, "usage: %s input.f\n", argv[0]);
        return 1;
    }

    FILE *fp = fopen(argv[1], "r");
    if (!fp) {
        perror("fopen");
        return 1;
    }

    tokenize(fp);
    fclose(fp);

    emit_header();
    compile_top();

    return 0;
}
