#!/usr/bin/env python3
# gen_matrix.py v1.1 - scc23 Phase1/C-1 テスト資材の生成/復元
# 設計書: scc23_C1_matrix_test_design_v0_4.md
#
# v1.1 変更: プロジェクトナレッジが tar.gz を扱えないため、
#            テストソース24 + 期待値24 + ディレクトリ構造を本スクリプトで
#            全て生成できるようにした（golden 12 は再生成不可のため
#            c1_goldens_bundle_v1_1.txt から展開する）。
#
# 使い方:
#   python3 gen_matrix.py                       # ソース+期待値+ディレクトリを生成
#   python3 gen_matrix.py --unbundle <bundle>   # golden を展開
#   python3 gen_matrix.py --all <bundle>        # 上記を一括実行
# 対象  : scc23 v2.05 (golden 基準版)
#
# KY 防止策3: 各ソースに「意図」をコメントで明記し、後から期待値の妥当性を検証可能にする。
# KY 防止策1: 期待値は本スクリプト内の EXPECT 表で先に確定させ、実測に合わせて書き換えない。

import os
import sys

# --- 期待値マトリクス（実装前に確定・実測に合わせて変更しないこと）---
# key: (rettype, op, rhs, proto) -> expect
#   rettype: 'i'=int, 'f'=float
#   op     : 'add'=+, 'div'=/
#   rhs    : 'k'=定数, 'v'=変数, 'c'=call
#   proto  : 'p'=プロトタイプあり, 'n'=なし
#
# 判定根拠:
#   proto='p'                 -> SC_FUNC 登録済みで型伝播が正しく効く      -> compile_ok
#   proto='n' かつ rettype='i'-> 未定義だが int 文脈なので T_INT が正解    -> warning_only
#   proto='n' かつ rettype='f'-> 未定義 call が float 文脈 -> 案D 発火     -> error_stop

def expect_of(rettype, proto):
    if proto == 'p':
        return 'compile_ok'
    if rettype == 'i':
        return 'warning_only'
    return 'error_stop'

OPSYM = {'add': '+', 'div': '/'}
TYNAME = {'i': 'int', 'f': 'float'}

# 右辺の式と、その右辺のために必要な補助宣言
def rhs_expr(rettype, rhs):
    if rhs == 'k':
        return ('2.0', '') if rettype == 'f' else ('2', '')
    if rhs == 'v':
        return ('rv', '')
    # rhs == 'c': 右辺も関数呼び出し。左辺と同じ getval を使うと
    # 「同一 call の二重評価」になり判定が曖昧になるため別名 getval2 を使う。
    return ('getval2()', '')

def gen_one(rettype, op, rhs, proto):
    name = "m1_%s_%s_%s_%s" % (rettype, op, rhs, proto)
    expect = expect_of(rettype, proto)
    ty = TYNAME[rettype]
    sym = OPSYM[op]
    rexpr, _ = rhs_expr(rettype, rhs)

    lines = []
    lines.append("/* %s.c" % name)
    lines.append(" * scc23 Phase1/C-1 matrix test  (generated by gen_matrix.py v1.0)")
    lines.append(" *")
    lines.append(" * 次元: 戻り値型=%s / 演算=%s / 右辺=%s / プロトタイプ=%s"
                 % (ty, sym, {'k': '定数', 'v': '変数', 'c': 'call'}[rhs],
                    'あり' if proto == 'p' else 'なし'))
    lines.append(" * 期待: %s" % expect)
    if expect == 'compile_ok':
        lines.append(" * 根拠: プロトタイプ宣言済み -> SC_FUNC 登録済みで戻り値型が正しく伝播する。")
        lines.append(" *       警告も error も出ず、golden asm と byte 一致すること。")
    elif expect == 'warning_only':
        lines.append(" * 根拠: 前方未定義だが int 文脈のみ。T_INT フォールバックが正解であり")
        lines.append(" *       コード生成は正常。案C の warning のみが出ること（error は出ない）。")
    else:
        lines.append(" * 根拠: 前方未定義 call が float 文脈に入る。案D が発火し error 停止すること。")
        lines.append(" *       (非0終了 AND \"used in float context\" メッセージ の AND 条件)")
    lines.append(" */")
    lines.append("")

    # プロトタイプ宣言（proto='p' のときのみ）
    if proto == 'p':
        lines.append("%s getval(void);" % ty)
        if rhs == 'c':
            lines.append("%s getval2(void);" % ty)
        lines.append("")

    # main
    lines.append("int main() {")
    lines.append("    %s x;" % ty)
    if rhs == 'v':
        # 右辺変数。float なら float 変数、int なら int 変数
        init = "3.0" if rettype == 'f' else "3"
        lines.append("    %s rv;" % ty)
        lines.append("    rv = %s;" % init)
    lines.append("    x = getval() %s %s;" % (sym, rexpr))
    lines.append("    return 0;")
    lines.append("}")
    lines.append("")

    # 関数本体（main より後ろ = 前方未定義になる配置）
    body = "2.5" if rettype == 'f' else "5"
    lines.append("%s getval(void) { return %s; }" % (ty, body))
    if rhs == 'c':
        body2 = "4.0" if rettype == 'f' else "4"
        lines.append("%s getval2(void) { return %s; }" % (ty, body2))
    lines.append("")

    return name, expect, "\n".join(lines)


def gen_expected(outdir, manifest):
    """期待値ファイル 24 個を生成（設計書 v0.4 §2.4）。

    golden 基準版は v2.06。
    error_stop の expect_error_contains は案G のメッセージのみを使う。
    案D の "used in float context" は片側 float の4ケースにしか出ないため
    一律指定すると両辺未定義ケースで AND 条件が成立せず FAIL する（§2.2.1）。
    """
    d = os.path.join(outdir, "expected")
    if not os.path.isdir(d):
        os.makedirs(d)
    for name, rt, op, rhs, pr, expect in manifest:
        path = os.path.join(d, name + ".expected")
        if pr == 'p':
            body = (
                "# %s.expected  (C-1 matrix / golden base scc23 v2.06)\n"
                "expect_result=compile_ok\n"
                "golden_version=v2.06\n"
                "golden_asm=goldens/%s.golden.asm\n" % (name, name))
        else:
            body = (
                "# %s.expected  (C-1 matrix / golden base scc23 v2.06)\n"
                "# 案G(undeclared call error)により proto=n は全て error_stop。\n"
                "# 注意: 案D の \"used in float context\" は片側floatの4ケースにしか出ないため\n"
                "#       一律指定禁止(両辺未定義callでAND条件不成立→FAIL)。設計書 v0.4 §2.2.1。\n"
                "expect_result=error_stop\n"
                "expect_error_contains=add a prototype declaration before use\n"
                "golden_version=v2.06\n" % name)
        with open(path, "w") as f:
            f.write(body)
    return len(manifest)


def unbundle_goldens(bundle_path, outdir):
    """c1_goldens_bundle_v1_1.txt から golden 12 件を展開する。

    golden は v2.06 で凍結した生成コードの実体であり再生成できない。
    ナレッジが tar.gz を扱えないため 1 ファイルに束ねて保存している。
    """
    d = os.path.join(outdir, "goldens")
    if not os.path.isdir(d):
        os.makedirs(d)
    cur_name = None
    cur_lines = []
    n = 0

    def flush(name, lines):
        # バンドル側は各ファイルの末尾改行1つだけを落としている。
        # 区切り行の直前に入る空行1つはセパレータ由来なので取り除く。
        body = lines[:]
        if body and body[-1] == "":
            body.pop()
        with open(os.path.join(d, name), "w") as g:
            g.write("\n".join(body) + "\n")

    with open(bundle_path) as f:
        for line in f:
            st = line.rstrip("\n")
            if st.startswith("==== FILE: ") and st.endswith(" ===="):
                if cur_name:
                    flush(cur_name, cur_lines)
                    n += 1
                cur_name = st[len("==== FILE: "):-len(" ====")].strip()
                cur_lines = []
            elif st == "==== END ====":
                if cur_name:
                    flush(cur_name, cur_lines)
                    n += 1
                cur_name = None
            elif cur_name is not None:
                cur_lines.append(st)
    return n


def main():
    outdir = os.path.dirname(os.path.abspath(__file__))

    # --unbundle モード
    if len(sys.argv) >= 2 and sys.argv[1] in ("--unbundle", "--all"):
        if len(sys.argv) < 3:
            print("usage: gen_matrix.py --unbundle <bundle.txt>")
            return 2
        n = unbundle_goldens(sys.argv[2], outdir)
        print("restored %d golden files into goldens/" % n)
        if sys.argv[1] == "--unbundle":
            return 0

    manifest = []
    for rettype in ('i', 'f'):
        for op in ('add', 'div'):
            for rhs in ('k', 'v', 'c'):
                for proto in ('p', 'n'):
                    name, expect, src = gen_one(rettype, op, rhs, proto)
                    with open(os.path.join(outdir, name + ".c"), "w") as f:
                        f.write(src)
                    manifest.append((name, rettype, op, rhs, proto, expect))

    # マニフェスト出力（README の期待値表の元データ）
    with open(os.path.join(outdir, "matrix_manifest.tsv"), "w") as f:
        f.write("name\trettype\top\trhs\tproto\texpect\n")
        for row in manifest:
            f.write("\t".join(row) + "\n")

    # 期待値ファイルと作業ディレクトリも生成（v1.1）
    n_exp = gen_expected(outdir, manifest)
    for sub in ("out", "corrupt_asms", "goldens"):
        p2 = os.path.join(outdir, sub)
        if not os.path.isdir(p2):
            os.makedirs(p2)

    n_ok = sum(1 for r in manifest if r[5] == 'compile_ok')
    n_wo = sum(1 for r in manifest if r[5] == 'warning_only')
    n_es = sum(1 for r in manifest if r[5] == 'error_stop')
    print("generated %d sources" % len(manifest))
    print("  compile_ok   : %d" % n_ok)
    print("  warning_only : %d" % n_wo)
    print("  error_stop   : %d" % n_es)
    print("generated %d expected files" % n_exp)
    print("created dirs: out/ corrupt_asms/ goldens/")
    print("")
    print("NOTE: golden 12 files are NOT generated (they are frozen v2.06 output).")
    print("      run:  python3 gen_matrix.py --unbundle c1_goldens_bundle_v1_1.txt")


if __name__ == "__main__":
    sys.exit(main() or 0)
